# Generated by Django 4.0.5 on 2023-01-15 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('ID_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_categoria', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('ID_compras', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_clase', models.CharField(max_length=30)),
                ('ID_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ID_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('Correo', models.CharField(max_length=30)),
                ('Clave', models.CharField(max_length=30)),
                ('Ubicacion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Compras',
            fields=[
                ('ID_estado_compras', models.AutoField(primary_key=True, serialize=False)),
                ('Estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ID_producto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Categoria', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=40)),
                ('Modelo', models.CharField(max_length=30)),
                ('Precio', models.IntegerField()),
                ('Cantidad', models.IntegerField()),
                ('ID_Clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clase')),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_Empleados',
            fields=[
                ('ID_tipo_emp', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('ID_ventas', models.AutoField(primary_key=True, serialize=False)),
                ('Precio', models.IntegerField()),
                ('Producto_vendidos', models.IntegerField()),
                ('Fecha', models.DateField()),
                ('ID_estado_compras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado_compras')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('ID_tienda', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Ubicacion', models.CharField(max_length=30)),
                ('ID_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('ID_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('ID_tipo_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipos_empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('ID_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Correo', models.CharField(max_length=30)),
                ('Clave', models.CharField(max_length=30)),
                ('ID_tipo_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipos_empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('ID_devoluciones', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Producto', models.CharField(max_length=30)),
                ('Fecha', models.DateField()),
                ('ID_Ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ventas')),
            ],
        ),
    ]
