# Generated by Django 4.1.5 on 2023-01-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Imagen_Producto',
            field=models.ImageField(null=True, upload_to='producto'),
        ),
    ]
